using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace PUSpecSheet.Data.Configurations;

public static class PublicIdBuilderExtensions
{
    /// <summary>
    /// Maps a stable public identifier: generated by SQL Server (sequential, so inserts stay cheap on the
    /// index), unique, and never changed after insert.
    /// </summary>
    public static EntityTypeBuilder<TEntity> HasPublicId<TEntity>(
        this EntityTypeBuilder<TEntity> builder,
        Expression<Func<TEntity, Guid>> publicId)
        where TEntity : class
    {
        var property = builder.Property(publicId)
            .HasDefaultValueSql("NEWSEQUENTIALID()")
            .ValueGeneratedOnAdd();
        property.Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Throw);

        builder.HasIndex(property.Metadata.Name)
            .IsUnique();

        return builder;
    }
}
