// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PUSpecSheet.Data;

#nullable disable

namespace PUSpecSheet.Data.Migrations
{
    [DbContext(typeof(PuSpecSheetDbContext))]
    [Migration("20260928200628_AddCellTypes")]
    partial class AddCellTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PUSpecSheet.Domain.CellTypes.CellType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DecimalPlaces")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MinValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CellTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fixed text such as a header.",
                            DisplayOrder = 1,
                            Kind = "Label",
                            Name = "Label"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Kind = "Text",
                            MaxLength = 200,
                            Name = "Text"
                        },
                        new
                        {
                            Id = 3,
                            DecimalPlaces = 2,
                            DisplayOrder = 3,
                            Kind = "Number",
                            Name = "Number"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Kind = "Date",
                            Name = "Date"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Kind = "Checkbox",
                            Name = "Checkbox"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Kind = "Dropdown",
                            Name = "Pass / Fail"
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.CellTypes.CellTypeOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CellTypeId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CellTypeId", "Value")
                        .IsUnique();

                    b.ToTable("CellTypeOptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CellTypeId = 6,
                            DisplayOrder = 1,
                            Value = "Pass"
                        },
                        new
                        {
                            Id = 2,
                            CellTypeId = 6,
                            DisplayOrder = 2,
                            Value = "Fail"
                        },
                        new
                        {
                            Id = 3,
                            CellTypeId = 6,
                            DisplayOrder = 3,
                            Value = "N/A"
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Phases.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("ParentPhaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentPhaseId");

                    b.ToTable("Phases", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Phases.PhaseSheetType", b =>
                {
                    b.Property<int>("PhaseId")
                        .HasColumnType("int");

                    b.Property<int>("SheetTypeId")
                        .HasColumnType("int");

                    b.HasKey("PhaseId", "SheetTypeId");

                    b.HasIndex("SheetTypeId");

                    b.ToTable("PhaseSheetTypes", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.SheetTypes.SheetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SheetTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Specification"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Parts"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "PFKs"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Engine Specifications"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Confirmation"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Torque Sheet"
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TableTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SheetTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SheetTypeId", "Name")
                        .IsUnique();

                    b.ToTable("TableTemplates", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CellTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Column")
                        .HasColumnType("int");

                    b.Property<int>("ColumnSpan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("RowSpan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("TemplateRowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CellTypeId");

                    b.HasIndex("TemplateRowId", "Column")
                        .IsUnique();

                    b.ToTable("TemplateCells", null, t =>
                        {
                            t.HasCheckConstraint("CK_TemplateCells_Column", "[Column] >= 1");

                            t.HasCheckConstraint("CK_TemplateCells_ColumnSpan", "[ColumnSpan] >= 1");

                            t.HasCheckConstraint("CK_TemplateCells_RowSpan", "[RowSpan] >= 1");
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("TemplateSectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplateSectionId");

                    b.ToTable("TemplateRows", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentSectionId")
                        .HasColumnType("int");

                    b.Property<int>("TableTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentSectionId");

                    b.HasIndex("TableTemplateId");

                    b.ToTable("TemplateSections", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.CellTypes.CellTypeOption", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.CellTypes.CellType", "CellType")
                        .WithMany("Options")
                        .HasForeignKey("CellTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CellType");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Phases.Phase", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Phases.Phase", "ParentPhase")
                        .WithMany("ChildPhases")
                        .HasForeignKey("ParentPhaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentPhase");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Phases.PhaseSheetType", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Phases.Phase", "Phase")
                        .WithMany("SheetTypes")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.SheetTypes.SheetType", "SheetType")
                        .WithMany("Phases")
                        .HasForeignKey("SheetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Phase");

                    b.Navigation("SheetType");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TableTemplate", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.SheetTypes.SheetType", "SheetType")
                        .WithMany()
                        .HasForeignKey("SheetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SheetType");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateCell", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.CellTypes.CellType", "CellType")
                        .WithMany()
                        .HasForeignKey("CellTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Templates.TemplateRow", "TemplateRow")
                        .WithMany("Cells")
                        .HasForeignKey("TemplateRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CellType");

                    b.Navigation("TemplateRow");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateRow", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Templates.TemplateSection", "TemplateSection")
                        .WithMany("Rows")
                        .HasForeignKey("TemplateSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateSection");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateSection", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Templates.TemplateSection", "ParentSection")
                        .WithMany("ChildSections")
                        .HasForeignKey("ParentSectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PUSpecSheet.Domain.Templates.TableTemplate", "TableTemplate")
                        .WithMany("Sections")
                        .HasForeignKey("TableTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentSection");

                    b.Navigation("TableTemplate");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.CellTypes.CellType", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Phases.Phase", b =>
                {
                    b.Navigation("ChildPhases");

                    b.Navigation("SheetTypes");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.SheetTypes.SheetType", b =>
                {
                    b.Navigation("Phases");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TableTemplate", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateRow", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateSection", b =>
                {
                    b.Navigation("ChildSections");

                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
