// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PUSpecSheet.Data;

#nullable disable

namespace PUSpecSheet.Data.Migrations
{
    [DbContext(typeof(PuSpecSheetDbContext))]
    [Migration("20260928201436_AddTypedCellValues")]
    partial class AddTypedCellValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PUSpecSheet.Domain.CellTypes.CellType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DecimalPlaces")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MinValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CellTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fixed text such as a header.",
                            DisplayOrder = 1,
                            Kind = "Label",
                            Name = "Label"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Kind = "Text",
                            MaxLength = 200,
                            Name = "Text"
                        },
                        new
                        {
                            Id = 3,
                            DecimalPlaces = 2,
                            DisplayOrder = 3,
                            Kind = "Number",
                            Name = "Number"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Kind = "Date",
                            Name = "Date"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Kind = "Checkbox",
                            Name = "Checkbox"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Kind = "Dropdown",
                            Name = "Pass / Fail"
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.CellTypes.CellTypeOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CellTypeId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CellTypeId", "Value")
                        .IsUnique();

                    b.ToTable("CellTypeOptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CellTypeId = 6,
                            DisplayOrder = 1,
                            Value = "Pass"
                        },
                        new
                        {
                            Id = 2,
                            CellTypeId = 6,
                            DisplayOrder = 2,
                            Value = "Fail"
                        },
                        new
                        {
                            Id = 3,
                            CellTypeId = 6,
                            DisplayOrder = 3,
                            Value = "N/A"
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Phases.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("ParentPhaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentPhaseId");

                    b.ToTable("Phases", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Phases.PhaseSheetType", b =>
                {
                    b.Property<int>("PhaseId")
                        .HasColumnType("int");

                    b.Property<int>("SheetTypeId")
                        .HasColumnType("int");

                    b.HasKey("PhaseId", "SheetTypeId");

                    b.HasIndex("SheetTypeId");

                    b.ToTable("PhaseSheetTypes", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.SheetTypes.SheetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SheetTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Specification"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Parts"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "PFKs"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Engine Specifications"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Confirmation"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Torque Sheet"
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.Sheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("PhaseId")
                        .HasColumnType("int");

                    b.Property<int>("SheetTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SheetTypeId");

                    b.HasIndex("PhaseId", "SheetTypeId")
                        .IsUnique();

                    b.ToTable("Sheets", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("SheetTableId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateRowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplateRowId");

                    b.HasIndex("SheetTableId", "DisplayOrder");

                    b.ToTable("SheetRows", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetRowRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<int>("SheetRowId")
                        .HasColumnType("int");

                    b.Property<int?>("SheetVersionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("SheetRowId")
                        .IsUnique()
                        .HasDatabaseName("UX_SheetRowRevisions_OneDraftPerRow")
                        .HasFilter("[Status] = 0");

                    b.HasIndex("SheetVersionId");

                    b.HasIndex("AuthorUserId", "Status");

                    b.HasIndex("SheetRowId", "PublishedAtUtc")
                        .HasDatabaseName("IX_SheetRowRevisions_Published")
                        .HasFilter("[Status] = 1");

                    b.HasIndex("SheetRowId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("SheetRowRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_SheetRowRevisions_PublishedAt", "([Status] = 0 AND [PublishedAtUtc] IS NULL) OR ([Status] = 1 AND [PublishedAtUtc] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("SheetId")
                        .HasColumnType("int");

                    b.Property<int>("TableTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TableTemplateId");

                    b.HasIndex("SheetId", "DisplayOrder");

                    b.ToTable("SheetTables", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PublishedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("SheetId")
                        .HasColumnType("int");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublishedByUserId");

                    b.HasIndex("SheetId", "PublishedAtUtc");

                    b.HasIndex("SheetId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("SheetVersions", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TableTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SheetTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SheetTypeId", "Name")
                        .IsUnique();

                    b.ToTable("TableTemplates", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CellTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Column")
                        .HasColumnType("int");

                    b.Property<int>("ColumnSpan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("RowSpan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("TemplateRowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CellTypeId");

                    b.HasIndex("TemplateRowId", "Column")
                        .IsUnique();

                    b.ToTable("TemplateCells", null, t =>
                        {
                            t.HasCheckConstraint("CK_TemplateCells_Column", "[Column] >= 1");

                            t.HasCheckConstraint("CK_TemplateCells_ColumnSpan", "[ColumnSpan] >= 1");

                            t.HasCheckConstraint("CK_TemplateCells_RowSpan", "[RowSpan] >= 1");
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("TemplateSectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplateSectionId");

                    b.ToTable("TemplateRows", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentSectionId")
                        .HasColumnType("int");

                    b.Property<int>("TableTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentSectionId");

                    b.HasIndex("TableTemplateId");

                    b.ToTable("TemplateSections", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Developer",
                            IsActive = true,
                            UserName = "developer"
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Values.BooleanValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SheetRowRevisionId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateCellId")
                        .HasColumnType("int");

                    b.Property<bool>("Value")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TemplateCellId");

                    b.HasIndex("SheetRowRevisionId", "TemplateCellId")
                        .IsUnique();

                    b.ToTable("BooleanValues", "values");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Values.DateValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SheetRowRevisionId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateCellId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Value")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("TemplateCellId");

                    b.HasIndex("SheetRowRevisionId", "TemplateCellId")
                        .IsUnique();

                    b.ToTable("DateValues", "values");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Values.NumericValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SheetRowRevisionId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateCellId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateCellId");

                    b.HasIndex("SheetRowRevisionId", "TemplateCellId")
                        .IsUnique();

                    b.ToTable("NumericValues", "values");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Values.OptionValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CellTypeOptionId")
                        .HasColumnType("int");

                    b.Property<int>("SheetRowRevisionId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateCellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CellTypeOptionId");

                    b.HasIndex("TemplateCellId");

                    b.HasIndex("SheetRowRevisionId", "TemplateCellId")
                        .IsUnique();

                    b.ToTable("OptionValues", "values");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Values.TextValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SheetRowRevisionId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateCellId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateCellId");

                    b.HasIndex("SheetRowRevisionId", "TemplateCellId")
                        .IsUnique();

                    b.ToTable("TextValues", "values");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.CellTypes.CellTypeOption", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.CellTypes.CellType", "CellType")
                        .WithMany("Options")
                        .HasForeignKey("CellTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CellType");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Phases.Phase", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Phases.Phase", "ParentPhase")
                        .WithMany("ChildPhases")
                        .HasForeignKey("ParentPhaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentPhase");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Phases.PhaseSheetType", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Phases.Phase", "Phase")
                        .WithMany("SheetTypes")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.SheetTypes.SheetType", "SheetType")
                        .WithMany("Phases")
                        .HasForeignKey("SheetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Phase");

                    b.Navigation("SheetType");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.Sheet", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Phases.Phase", "Phase")
                        .WithMany()
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.SheetTypes.SheetType", "SheetType")
                        .WithMany()
                        .HasForeignKey("SheetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Phase");

                    b.Navigation("SheetType");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetRow", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetTable", "SheetTable")
                        .WithMany("Rows")
                        .HasForeignKey("SheetTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Templates.TemplateRow", "TemplateRow")
                        .WithMany()
                        .HasForeignKey("TemplateRowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SheetTable");

                    b.Navigation("TemplateRow");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetRowRevision", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Users.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetRow", "SheetRow")
                        .WithMany("Revisions")
                        .HasForeignKey("SheetRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetVersion", "SheetVersion")
                        .WithMany("RowRevisions")
                        .HasForeignKey("SheetVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Author");

                    b.Navigation("SheetRow");

                    b.Navigation("SheetVersion");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetTable", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Sheets.Sheet", "Sheet")
                        .WithMany("Tables")
                        .HasForeignKey("SheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Templates.TableTemplate", "TableTemplate")
                        .WithMany()
                        .HasForeignKey("TableTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sheet");

                    b.Navigation("TableTemplate");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetVersion", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Users.User", "PublishedBy")
                        .WithMany()
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Sheets.Sheet", "Sheet")
                        .WithMany("Versions")
                        .HasForeignKey("SheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublishedBy");

                    b.Navigation("Sheet");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TableTemplate", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.SheetTypes.SheetType", "SheetType")
                        .WithMany()
                        .HasForeignKey("SheetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SheetType");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateCell", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.CellTypes.CellType", "CellType")
                        .WithMany()
                        .HasForeignKey("CellTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Templates.TemplateRow", "TemplateRow")
                        .WithMany("Cells")
                        .HasForeignKey("TemplateRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CellType");

                    b.Navigation("TemplateRow");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateRow", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Templates.TemplateSection", "TemplateSection")
                        .WithMany("Rows")
                        .HasForeignKey("TemplateSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateSection");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateSection", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Templates.TemplateSection", "ParentSection")
                        .WithMany("ChildSections")
                        .HasForeignKey("ParentSectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PUSpecSheet.Domain.Templates.TableTemplate", "TableTemplate")
                        .WithMany("Sections")
                        .HasForeignKey("TableTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentSection");

                    b.Navigation("TableTemplate");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Values.BooleanValue", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetRowRevision", "SheetRowRevision")
                        .WithMany("BooleanValues")
                        .HasForeignKey("SheetRowRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Templates.TemplateCell", "TemplateCell")
                        .WithMany()
                        .HasForeignKey("TemplateCellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SheetRowRevision");

                    b.Navigation("TemplateCell");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Values.DateValue", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetRowRevision", "SheetRowRevision")
                        .WithMany("DateValues")
                        .HasForeignKey("SheetRowRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Templates.TemplateCell", "TemplateCell")
                        .WithMany()
                        .HasForeignKey("TemplateCellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SheetRowRevision");

                    b.Navigation("TemplateCell");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Values.NumericValue", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetRowRevision", "SheetRowRevision")
                        .WithMany("NumericValues")
                        .HasForeignKey("SheetRowRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Templates.TemplateCell", "TemplateCell")
                        .WithMany()
                        .HasForeignKey("TemplateCellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SheetRowRevision");

                    b.Navigation("TemplateCell");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Values.OptionValue", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.CellTypes.CellTypeOption", "CellTypeOption")
                        .WithMany()
                        .HasForeignKey("CellTypeOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetRowRevision", "SheetRowRevision")
                        .WithMany("OptionValues")
                        .HasForeignKey("SheetRowRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Templates.TemplateCell", "TemplateCell")
                        .WithMany()
                        .HasForeignKey("TemplateCellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CellTypeOption");

                    b.Navigation("SheetRowRevision");

                    b.Navigation("TemplateCell");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Values.TextValue", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetRowRevision", "SheetRowRevision")
                        .WithMany("TextValues")
                        .HasForeignKey("SheetRowRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Templates.TemplateCell", "TemplateCell")
                        .WithMany()
                        .HasForeignKey("TemplateCellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SheetRowRevision");

                    b.Navigation("TemplateCell");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.CellTypes.CellType", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Phases.Phase", b =>
                {
                    b.Navigation("ChildPhases");

                    b.Navigation("SheetTypes");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.SheetTypes.SheetType", b =>
                {
                    b.Navigation("Phases");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.Sheet", b =>
                {
                    b.Navigation("Tables");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetRow", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetRowRevision", b =>
                {
                    b.Navigation("BooleanValues");

                    b.Navigation("DateValues");

                    b.Navigation("NumericValues");

                    b.Navigation("OptionValues");

                    b.Navigation("TextValues");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetTable", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetVersion", b =>
                {
                    b.Navigation("RowRevisions");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TableTemplate", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateRow", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateSection", b =>
                {
                    b.Navigation("ChildSections");

                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
