// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PUSpecSheet.Data;

#nullable disable

namespace PUSpecSheet.Data.Migrations
{
    [DbContext(typeof(PuSpecSheetDbContext))]
    [Migration("20261001193056_AddColumnBlocks")]
    partial class AddColumnBlocks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PUSpecSheet.Domain.CellTypes.CellType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CellTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Configuration = "{\"kind\":\"Heading\"}",
                            Description = "Fixed text such as a column header.",
                            DisplayOrder = 1,
                            Kind = "Heading",
                            Name = "Heading",
                            Style = "{\"bold\":true}"
                        },
                        new
                        {
                            Id = 2,
                            Configuration = "{\"kind\":\"Text\",\"maxLength\":200}",
                            DisplayOrder = 2,
                            Kind = "Text",
                            Name = "Text",
                            Style = "{}"
                        },
                        new
                        {
                            Id = 3,
                            Configuration = "{\"kind\":\"Number\",\"decimalPlaces\":2}",
                            DisplayOrder = 3,
                            Kind = "Number",
                            Name = "Number",
                            Style = "{\"align\":\"Right\"}"
                        },
                        new
                        {
                            Id = 4,
                            Configuration = "{\"kind\":\"Date\"}",
                            DisplayOrder = 4,
                            Kind = "Date",
                            Name = "Date",
                            Style = "{}"
                        },
                        new
                        {
                            Id = 5,
                            Configuration = "{\"kind\":\"Checkbox\"}",
                            DisplayOrder = 5,
                            Kind = "Checkbox",
                            Name = "Checkbox",
                            Style = "{\"align\":\"Center\"}"
                        },
                        new
                        {
                            Id = 6,
                            Configuration = "{\"kind\":\"TextDropdown\"}",
                            DisplayOrder = 6,
                            Kind = "TextDropdown",
                            Name = "Pass / Fail",
                            Style = "{}"
                        },
                        new
                        {
                            Id = 7,
                            Configuration = "{\"kind\":\"Group\"}",
                            Description = "A caption that groups the cells around it.",
                            DisplayOrder = 7,
                            Kind = "Group",
                            Name = "Group",
                            Style = "{\"bold\":true,\"backgroundColor\":\"#f1f5f9\"}"
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.CellTypes.CellTypeOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CellTypeId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CellTypeId", "Value")
                        .IsUnique();

                    b.ToTable("CellTypeOptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CellTypeId = 6,
                            DisplayOrder = 1,
                            Value = "Pass"
                        },
                        new
                        {
                            Id = 2,
                            CellTypeId = 6,
                            DisplayOrder = 2,
                            Value = "Fail"
                        },
                        new
                        {
                            Id = 3,
                            CellTypeId = 6,
                            DisplayOrder = 3,
                            Value = "N/A"
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Phases.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("ParentPhaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentPhaseId");

                    b.ToTable("Phases", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Phases.PhaseSheetType", b =>
                {
                    b.Property<int>("PhaseId")
                        .HasColumnType("int");

                    b.Property<int>("SheetTypeId")
                        .HasColumnType("int");

                    b.HasKey("PhaseId", "SheetTypeId");

                    b.HasIndex("SheetTypeId");

                    b.ToTable("PhaseSheetTypes", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.SheetTypes.SheetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SheetTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Specification"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Parts"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "PFKs"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Engine Specifications"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Confirmation"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Torque Sheet"
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.Sheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("PhaseId")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SheetTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SheetTypeId");

                    b.HasIndex("PhaseId", "SheetTypeId")
                        .IsUnique();

                    b.ToTable("Sheets", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int?>("SheetColumnBlockId")
                        .HasColumnType("int");

                    b.Property<int>("SheetRowId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateCellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SheetColumnBlockId");

                    b.HasIndex("TemplateCellId");

                    b.HasIndex("SheetRowId", "TemplateCellId", "SheetColumnBlockId")
                        .IsUnique();

                    b.ToTable("SheetCells", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetColumnBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("SheetTableId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateColumnBlockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SheetTableId");

                    b.HasIndex("TemplateColumnBlockId");

                    b.ToTable("SheetColumnBlocks", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetColumnBlockRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SheetColumnBlockId")
                        .HasColumnType("int");

                    b.Property<int?>("SheetVersionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SupersededAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("SheetVersionId");

                    b.HasIndex("AuthorUserId", "Status");

                    b.HasIndex("SheetColumnBlockId", "PublishedAtUtc")
                        .HasDatabaseName("IX_SheetColumnBlockRevisions_Published")
                        .HasFilter("[Status] = 1");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SheetColumnBlockId", "PublishedAtUtc"), new[] { "SupersededAtUtc" });

                    b.HasIndex("SheetColumnBlockId", "RevisionNumber")
                        .IsUnique();

                    b.HasIndex(new[] { "SheetColumnBlockId" }, "UX_SheetColumnBlockRevisions_OneCurrentPerBlock")
                        .IsUnique()
                        .HasFilter("[Status] = 1 AND [SupersededAtUtc] IS NULL");

                    b.HasIndex(new[] { "SheetColumnBlockId" }, "UX_SheetColumnBlockRevisions_OneDraftPerBlock")
                        .IsUnique()
                        .HasFilter("[Status] = 0");

                    b.ToTable("SheetColumnBlockRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_SheetColumnBlockRevisions_PublishedAt", "([Status] = 0 AND [PublishedAtUtc] IS NULL) OR ([Status] = 1 AND [PublishedAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_SheetColumnBlockRevisions_SupersededAt", "[SupersededAtUtc] IS NULL OR ([Status] = 1 AND [SupersededAtUtc] >= [PublishedAtUtc])");
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("SheetSectionId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateRowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SheetSectionId");

                    b.HasIndex("TemplateRowId");

                    b.ToTable("SheetRows", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetRowRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SheetRowId")
                        .HasColumnType("int");

                    b.Property<int?>("SheetVersionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SupersededAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("SheetVersionId");

                    b.HasIndex("AuthorUserId", "Status");

                    b.HasIndex("SheetRowId", "PublishedAtUtc")
                        .HasDatabaseName("IX_SheetRowRevisions_Published")
                        .HasFilter("[Status] = 1");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SheetRowId", "PublishedAtUtc"), new[] { "SupersededAtUtc" });

                    b.HasIndex("SheetRowId", "RevisionNumber")
                        .IsUnique();

                    b.HasIndex(new[] { "SheetRowId" }, "UX_SheetRowRevisions_OneCurrentPerRow")
                        .IsUnique()
                        .HasFilter("[Status] = 1 AND [SupersededAtUtc] IS NULL");

                    b.HasIndex(new[] { "SheetRowId" }, "UX_SheetRowRevisions_OneDraftPerRow")
                        .IsUnique()
                        .HasFilter("[Status] = 0");

                    b.ToTable("SheetRowRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_SheetRowRevisions_PublishedAt", "([Status] = 0 AND [PublishedAtUtc] IS NULL) OR ([Status] = 1 AND [PublishedAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_SheetRowRevisions_SupersededAt", "[SupersededAtUtc] IS NULL OR ([Status] = 1 AND [SupersededAtUtc] >= [PublishedAtUtc])");
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("ParentSheetSectionId")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("SheetTableId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateSectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentSheetSectionId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SheetTableId");

                    b.HasIndex("TemplateSectionId");

                    b.ToTable("SheetSections", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetSectionRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SheetSectionId")
                        .HasColumnType("int");

                    b.Property<int?>("SheetVersionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SupersededAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("SheetVersionId");

                    b.HasIndex("AuthorUserId", "Status");

                    b.HasIndex("SheetSectionId", "PublishedAtUtc")
                        .HasDatabaseName("IX_SheetSectionRevisions_Published")
                        .HasFilter("[Status] = 1");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SheetSectionId", "PublishedAtUtc"), new[] { "SupersededAtUtc" });

                    b.HasIndex("SheetSectionId", "RevisionNumber")
                        .IsUnique();

                    b.HasIndex(new[] { "SheetSectionId" }, "UX_SheetSectionRevisions_OneCurrentPerSection")
                        .IsUnique()
                        .HasFilter("[Status] = 1 AND [SupersededAtUtc] IS NULL");

                    b.HasIndex(new[] { "SheetSectionId" }, "UX_SheetSectionRevisions_OneDraftPerSection")
                        .IsUnique()
                        .HasFilter("[Status] = 0");

                    b.ToTable("SheetSectionRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_SheetSectionRevisions_PublishedAt", "([Status] = 0 AND [PublishedAtUtc] IS NULL) OR ([Status] = 1 AND [PublishedAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_SheetSectionRevisions_SupersededAt", "[SupersededAtUtc] IS NULL OR ([Status] = 1 AND [SupersededAtUtc] >= [PublishedAtUtc])");
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("SheetId")
                        .HasColumnType("int");

                    b.Property<int>("TableTemplateVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SheetId");

                    b.HasIndex("TableTemplateVersionId");

                    b.ToTable("SheetTables", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetTableRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SheetTableId")
                        .HasColumnType("int");

                    b.Property<int?>("SheetVersionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SupersededAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("SheetVersionId");

                    b.HasIndex("AuthorUserId", "Status");

                    b.HasIndex("SheetTableId", "PublishedAtUtc")
                        .HasDatabaseName("IX_SheetTableRevisions_Published")
                        .HasFilter("[Status] = 1");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SheetTableId", "PublishedAtUtc"), new[] { "SupersededAtUtc" });

                    b.HasIndex("SheetTableId", "RevisionNumber")
                        .IsUnique();

                    b.HasIndex(new[] { "SheetTableId" }, "UX_SheetTableRevisions_OneCurrentPerTable")
                        .IsUnique()
                        .HasFilter("[Status] = 1 AND [SupersededAtUtc] IS NULL");

                    b.HasIndex(new[] { "SheetTableId" }, "UX_SheetTableRevisions_OneDraftPerTable")
                        .IsUnique()
                        .HasFilter("[Status] = 0");

                    b.ToTable("SheetTableRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_SheetTableRevisions_PublishedAt", "([Status] = 0 AND [PublishedAtUtc] IS NULL) OR ([Status] = 1 AND [PublishedAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_SheetTableRevisions_SupersededAt", "[SupersededAtUtc] IS NULL OR ([Status] = 1 AND [SupersededAtUtc] >= [PublishedAtUtc])");
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PublishedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("SheetId")
                        .HasColumnType("int");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublishedByUserId");

                    b.HasIndex("SheetId", "PublishedAtUtc");

                    b.HasIndex("SheetId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("SheetVersions", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TableTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SheetTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SheetTypeId", "Name")
                        .IsUnique();

                    b.ToTable("TableTemplates", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TableTemplateVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TableTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TableTemplateId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("TableTemplateVersions", null, t =>
                        {
                            t.HasCheckConstraint("CK_TableTemplateVersions_VersionNumber", "[VersionNumber] >= 1");
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CellTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Column")
                        .HasColumnType("int");

                    b.Property<int>("ColumnSpan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("ConfigurationOverride")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("RowSpan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("StyleOverride")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TemplateColumnBlockId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateRowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CellTypeId");

                    b.HasIndex("TemplateColumnBlockId");

                    b.HasIndex("TemplateRowId", "TemplateColumnBlockId", "Column")
                        .IsUnique();

                    b.ToTable("TemplateCells", null, t =>
                        {
                            t.HasCheckConstraint("CK_TemplateCells_Column", "[Column] >= 1");

                            t.HasCheckConstraint("CK_TemplateCells_ColumnSpan", "[ColumnSpan] >= 1");

                            t.HasCheckConstraint("CK_TemplateCells_RowSpan", "[RowSpan] >= 1");
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateColumnBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("InitialInstances")
                        .HasColumnType("int");

                    b.Property<int?>("MaxInstances")
                        .HasColumnType("int");

                    b.Property<int>("MinInstances")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TableTemplateVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TableTemplateVersionId");

                    b.ToTable("TemplateColumnBlocks", null, t =>
                        {
                            t.HasCheckConstraint("CK_TemplateColumnBlocks_Instances", "[MinInstances] >= 0 AND [InitialInstances] >= [MinInstances] AND ([MaxInstances] IS NULL OR ([MaxInstances] >= 1 AND [MaxInstances] >= [InitialInstances]))");
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("TemplateSectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplateSectionId");

                    b.ToTable("TemplateRows", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("InitialInstances")
                        .HasColumnType("int");

                    b.Property<int?>("MaxInstances")
                        .HasColumnType("int");

                    b.Property<int>("MinInstances")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentSectionId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TableTemplateVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentSectionId");

                    b.HasIndex("TableTemplateVersionId");

                    b.HasIndex(new[] { "TableTemplateVersionId" }, "UX_TemplateSections_OneHeaderPerVersion")
                        .IsUnique()
                        .HasFilter("[Role] = 'Header'");

                    b.ToTable("TemplateSections", null, t =>
                        {
                            t.HasCheckConstraint("CK_TemplateSections_Header", "[Role] <> 'Header' OR ([ParentSectionId] IS NULL AND [MinInstances] = 1 AND [MaxInstances] = 1 AND [InitialInstances] = 1)");

                            t.HasCheckConstraint("CK_TemplateSections_Instances", "[MinInstances] >= 0 AND [InitialInstances] >= [MinInstances] AND ([MaxInstances] IS NULL OR ([MaxInstances] >= 1 AND [MaxInstances] >= [InitialInstances]))");
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Developer",
                            IsActive = true,
                            UserName = "developer"
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Values.BooleanValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SheetCellId")
                        .HasColumnType("int");

                    b.Property<int>("SheetRowRevisionId")
                        .HasColumnType("int");

                    b.Property<bool>("Value")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SheetCellId");

                    b.HasIndex("SheetRowRevisionId", "SheetCellId")
                        .IsUnique();

                    b.ToTable("BooleanValues", "values");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Values.DateValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SheetCellId")
                        .HasColumnType("int");

                    b.Property<int>("SheetRowRevisionId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Value")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("SheetCellId");

                    b.HasIndex("SheetRowRevisionId", "SheetCellId")
                        .IsUnique();

                    b.ToTable("DateValues", "values");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Values.NumericValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SheetCellId")
                        .HasColumnType("int");

                    b.Property<int>("SheetRowRevisionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.HasKey("Id");

                    b.HasIndex("SheetCellId");

                    b.HasIndex("SheetRowRevisionId", "SheetCellId")
                        .IsUnique();

                    b.ToTable("NumericValues", "values");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Values.OptionValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CellTypeOptionId")
                        .HasColumnType("int");

                    b.Property<int>("SheetCellId")
                        .HasColumnType("int");

                    b.Property<int>("SheetRowRevisionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CellTypeOptionId");

                    b.HasIndex("SheetCellId");

                    b.HasIndex("SheetRowRevisionId", "SheetCellId")
                        .IsUnique();

                    b.ToTable("OptionValues", "values");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Values.TextValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SheetCellId")
                        .HasColumnType("int");

                    b.Property<int>("SheetRowRevisionId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("SheetCellId");

                    b.HasIndex("SheetRowRevisionId", "SheetCellId")
                        .IsUnique();

                    b.ToTable("TextValues", "values");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.CellTypes.CellTypeOption", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.CellTypes.CellType", "CellType")
                        .WithMany("Options")
                        .HasForeignKey("CellTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CellType");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Phases.Phase", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Phases.Phase", "ParentPhase")
                        .WithMany("ChildPhases")
                        .HasForeignKey("ParentPhaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentPhase");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Phases.PhaseSheetType", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Phases.Phase", "Phase")
                        .WithMany("SheetTypes")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.SheetTypes.SheetType", "SheetType")
                        .WithMany("Phases")
                        .HasForeignKey("SheetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Phase");

                    b.Navigation("SheetType");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.Sheet", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Phases.Phase", "Phase")
                        .WithMany()
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.SheetTypes.SheetType", "SheetType")
                        .WithMany()
                        .HasForeignKey("SheetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Phase");

                    b.Navigation("SheetType");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetCell", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetColumnBlock", "SheetColumnBlock")
                        .WithMany("Cells")
                        .HasForeignKey("SheetColumnBlockId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetRow", "SheetRow")
                        .WithMany("Cells")
                        .HasForeignKey("SheetRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Templates.TemplateCell", "TemplateCell")
                        .WithMany()
                        .HasForeignKey("TemplateCellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SheetColumnBlock");

                    b.Navigation("SheetRow");

                    b.Navigation("TemplateCell");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetColumnBlock", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetTable", "SheetTable")
                        .WithMany("ColumnBlocks")
                        .HasForeignKey("SheetTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Templates.TemplateColumnBlock", "TemplateColumnBlock")
                        .WithMany()
                        .HasForeignKey("TemplateColumnBlockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SheetTable");

                    b.Navigation("TemplateColumnBlock");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetColumnBlockRevision", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Users.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetColumnBlock", "SheetColumnBlock")
                        .WithMany("Revisions")
                        .HasForeignKey("SheetColumnBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetVersion", "SheetVersion")
                        .WithMany("ColumnBlockRevisions")
                        .HasForeignKey("SheetVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Author");

                    b.Navigation("SheetColumnBlock");

                    b.Navigation("SheetVersion");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetRow", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetSection", "SheetSection")
                        .WithMany("Rows")
                        .HasForeignKey("SheetSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Templates.TemplateRow", "TemplateRow")
                        .WithMany()
                        .HasForeignKey("TemplateRowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SheetSection");

                    b.Navigation("TemplateRow");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetRowRevision", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Users.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetRow", "SheetRow")
                        .WithMany("Revisions")
                        .HasForeignKey("SheetRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetVersion", "SheetVersion")
                        .WithMany("RowRevisions")
                        .HasForeignKey("SheetVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Author");

                    b.Navigation("SheetRow");

                    b.Navigation("SheetVersion");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetSection", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetSection", "ParentSheetSection")
                        .WithMany("ChildSheetSections")
                        .HasForeignKey("ParentSheetSectionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetTable", "SheetTable")
                        .WithMany("Sections")
                        .HasForeignKey("SheetTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Templates.TemplateSection", "TemplateSection")
                        .WithMany()
                        .HasForeignKey("TemplateSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentSheetSection");

                    b.Navigation("SheetTable");

                    b.Navigation("TemplateSection");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetSectionRevision", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Users.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetSection", "SheetSection")
                        .WithMany("Revisions")
                        .HasForeignKey("SheetSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetVersion", "SheetVersion")
                        .WithMany("SectionRevisions")
                        .HasForeignKey("SheetVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Author");

                    b.Navigation("SheetSection");

                    b.Navigation("SheetVersion");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetTable", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Sheets.Sheet", "Sheet")
                        .WithMany("Tables")
                        .HasForeignKey("SheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Templates.TableTemplateVersion", "TableTemplateVersion")
                        .WithMany()
                        .HasForeignKey("TableTemplateVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sheet");

                    b.Navigation("TableTemplateVersion");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetTableRevision", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Users.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetTable", "SheetTable")
                        .WithMany("Revisions")
                        .HasForeignKey("SheetTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetVersion", "SheetVersion")
                        .WithMany("TableRevisions")
                        .HasForeignKey("SheetVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Author");

                    b.Navigation("SheetTable");

                    b.Navigation("SheetVersion");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetVersion", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Users.User", "PublishedBy")
                        .WithMany()
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Sheets.Sheet", "Sheet")
                        .WithMany("Versions")
                        .HasForeignKey("SheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublishedBy");

                    b.Navigation("Sheet");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TableTemplate", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.SheetTypes.SheetType", "SheetType")
                        .WithMany()
                        .HasForeignKey("SheetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SheetType");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TableTemplateVersion", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Templates.TableTemplate", "TableTemplate")
                        .WithMany("Versions")
                        .HasForeignKey("TableTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableTemplate");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateCell", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.CellTypes.CellType", "CellType")
                        .WithMany()
                        .HasForeignKey("CellTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Templates.TemplateColumnBlock", "TemplateColumnBlock")
                        .WithMany("Cells")
                        .HasForeignKey("TemplateColumnBlockId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PUSpecSheet.Domain.Templates.TemplateRow", "TemplateRow")
                        .WithMany("Cells")
                        .HasForeignKey("TemplateRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CellType");

                    b.Navigation("TemplateColumnBlock");

                    b.Navigation("TemplateRow");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateColumnBlock", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Templates.TableTemplateVersion", "TableTemplateVersion")
                        .WithMany("ColumnBlocks")
                        .HasForeignKey("TableTemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableTemplateVersion");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateRow", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Templates.TemplateSection", "TemplateSection")
                        .WithMany("Rows")
                        .HasForeignKey("TemplateSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateSection");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateSection", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Templates.TemplateSection", "ParentSection")
                        .WithMany("ChildSections")
                        .HasForeignKey("ParentSectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PUSpecSheet.Domain.Templates.TableTemplateVersion", "TableTemplateVersion")
                        .WithMany("Sections")
                        .HasForeignKey("TableTemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentSection");

                    b.Navigation("TableTemplateVersion");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Values.BooleanValue", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetCell", "SheetCell")
                        .WithMany()
                        .HasForeignKey("SheetCellId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetRowRevision", "SheetRowRevision")
                        .WithMany("BooleanValues")
                        .HasForeignKey("SheetRowRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SheetCell");

                    b.Navigation("SheetRowRevision");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Values.DateValue", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetCell", "SheetCell")
                        .WithMany()
                        .HasForeignKey("SheetCellId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetRowRevision", "SheetRowRevision")
                        .WithMany("DateValues")
                        .HasForeignKey("SheetRowRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SheetCell");

                    b.Navigation("SheetRowRevision");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Values.NumericValue", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetCell", "SheetCell")
                        .WithMany()
                        .HasForeignKey("SheetCellId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetRowRevision", "SheetRowRevision")
                        .WithMany("NumericValues")
                        .HasForeignKey("SheetRowRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SheetCell");

                    b.Navigation("SheetRowRevision");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Values.OptionValue", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.CellTypes.CellTypeOption", "CellTypeOption")
                        .WithMany()
                        .HasForeignKey("CellTypeOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetCell", "SheetCell")
                        .WithMany()
                        .HasForeignKey("SheetCellId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetRowRevision", "SheetRowRevision")
                        .WithMany("OptionValues")
                        .HasForeignKey("SheetRowRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CellTypeOption");

                    b.Navigation("SheetCell");

                    b.Navigation("SheetRowRevision");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Values.TextValue", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetCell", "SheetCell")
                        .WithMany()
                        .HasForeignKey("SheetCellId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.Sheets.SheetRowRevision", "SheetRowRevision")
                        .WithMany("TextValues")
                        .HasForeignKey("SheetRowRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SheetCell");

                    b.Navigation("SheetRowRevision");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.CellTypes.CellType", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Phases.Phase", b =>
                {
                    b.Navigation("ChildPhases");

                    b.Navigation("SheetTypes");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.SheetTypes.SheetType", b =>
                {
                    b.Navigation("Phases");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.Sheet", b =>
                {
                    b.Navigation("Tables");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetColumnBlock", b =>
                {
                    b.Navigation("Cells");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetRow", b =>
                {
                    b.Navigation("Cells");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetRowRevision", b =>
                {
                    b.Navigation("BooleanValues");

                    b.Navigation("DateValues");

                    b.Navigation("NumericValues");

                    b.Navigation("OptionValues");

                    b.Navigation("TextValues");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetSection", b =>
                {
                    b.Navigation("ChildSheetSections");

                    b.Navigation("Revisions");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetTable", b =>
                {
                    b.Navigation("ColumnBlocks");

                    b.Navigation("Revisions");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Sheets.SheetVersion", b =>
                {
                    b.Navigation("ColumnBlockRevisions");

                    b.Navigation("RowRevisions");

                    b.Navigation("SectionRevisions");

                    b.Navigation("TableRevisions");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TableTemplate", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TableTemplateVersion", b =>
                {
                    b.Navigation("ColumnBlocks");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateColumnBlock", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateRow", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Templates.TemplateSection", b =>
                {
                    b.Navigation("ChildSections");

                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
