// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PUSpecSheet.Data;

#nullable disable

namespace PUSpecSheet.Data.Migrations
{
    [DbContext(typeof(PuSpecSheetDbContext))]
    [Migration("20260928192830_InitialPhasesAndSheetTypes")]
    partial class InitialPhasesAndSheetTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PUSpecSheet.Domain.Phases.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("ParentPhaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentPhaseId");

                    b.ToTable("Phases", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Phases.PhaseSheetType", b =>
                {
                    b.Property<int>("PhaseId")
                        .HasColumnType("int");

                    b.Property<int>("SheetTypeId")
                        .HasColumnType("int");

                    b.HasKey("PhaseId", "SheetTypeId");

                    b.HasIndex("SheetTypeId");

                    b.ToTable("PhaseSheetTypes", (string)null);
                });

            modelBuilder.Entity("PUSpecSheet.Domain.SheetTypes.SheetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SheetTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Specification"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Parts"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "PFKs"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Engine Specifications"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Confirmation"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Torque Sheet"
                        });
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Phases.Phase", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Phases.Phase", "ParentPhase")
                        .WithMany("ChildPhases")
                        .HasForeignKey("ParentPhaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentPhase");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Phases.PhaseSheetType", b =>
                {
                    b.HasOne("PUSpecSheet.Domain.Phases.Phase", "Phase")
                        .WithMany("SheetTypes")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSpecSheet.Domain.SheetTypes.SheetType", "SheetType")
                        .WithMany("Phases")
                        .HasForeignKey("SheetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Phase");

                    b.Navigation("SheetType");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.Phases.Phase", b =>
                {
                    b.Navigation("ChildPhases");

                    b.Navigation("SheetTypes");
                });

            modelBuilder.Entity("PUSpecSheet.Domain.SheetTypes.SheetType", b =>
                {
                    b.Navigation("Phases");
                });
#pragma warning restore 612, 618
        }
    }
}
