<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.13" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PUSpecSheet.Application\PUSpecSheet.Application.csproj" />
    <ProjectReference Include="..\PUSpecSheet.Contracts\PUSpecSheet.Contracts.csproj" />
    <ProjectReference Include="..\PUSpecSheet.Data\PUSpecSheet.Data.csproj" />
  </ItemGroup>
</Project>